src/videoserver/apps/swagger/__init__.py
from flask import Blueprint

bp = Blueprint('swagger', __name__, template_folder='templates', static_folder='static')

from . import routes # noqa


def init_app(app):
    app.register_blueprint(bp, url_prefix='/swagger')

src/videoserver/apps/swagger/routes.py
from flask import current_app as app
from flask import render_template, jsonify
from flask_swagger import swagger

from . import bp


@bp.route('/spec')
def spec_data():
    swag = swagger(app)
    swag['info']['version'] = "0.1"
    swag['info']['title'] = "Video editor API"
    return jsonify(swag)


@bp.route('/')
def swag():
    return render_template('index.html')

src/videoserver/apps/swagger/templates/index.html
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('swagger.static', filename='swagger-ui.css') }}" >
    <link rel="icon" type="image/png" href="{{ url_for('swagger.static', filename='favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{{ url_for('swagger.static', filename='favicon-16x16.png') }}" sizes="16x16" />
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>

    <script src="{{ url_for('swagger.static', filename='swagger-ui-bundle.js') }}"> </script>
    <script src="{{ url_for('swagger.static', filename='swagger-ui-standalone-preset.js') }}"> </script>
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "{{ url_for('swagger.spec_data') }}",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      })
      // End Swagger UI call region

      window.ui = ui
    }
  </script>
  </body>
</html>